// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGO3OIF45IGEKXnv3gxlzQw5fmjM0M-K0',
    appId: '1:472233370860:web:49408898e042f10d72f1c9',
    messagingSenderId: '472233370860',
    projectId: 'voxbridge-cf7be',
    authDomain: 'voxbridge-cf7be.firebaseapp.com',
    storageBucket: 'voxbridge-cf7be.firebasestorage.app',
    measurementId: 'G-4DD7QNS0C2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgDxd7wLUL0YOIZUFkwRp_As5j4QmzHVQ',
    appId: '1:472233370860:android:e6c4c45f137d736572f1c9',
    messagingSenderId: '472233370860',
    projectId: 'voxbridge-cf7be',
    storageBucket: 'voxbridge-cf7be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWmAARR5tYxmpI2mrfgjNcjBLQZPVlQiA',
    appId: '1:472233370860:ios:20b82089d71d863772f1c9',
    messagingSenderId: '472233370860',
    projectId: 'voxbridge-cf7be',
    storageBucket: 'voxbridge-cf7be.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWmAARR5tYxmpI2mrfgjNcjBLQZPVlQiA',
    appId: '1:472233370860:ios:20b82089d71d863772f1c9',
    messagingSenderId: '472233370860',
    projectId: 'voxbridge-cf7be',
    storageBucket: 'voxbridge-cf7be.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGO3OIF45IGEKXnv3gxlzQw5fmjM0M-K0',
    appId: '1:472233370860:web:3c3b402aa33e144c72f1c9',
    messagingSenderId: '472233370860',
    projectId: 'voxbridge-cf7be',
    authDomain: 'voxbridge-cf7be.firebaseapp.com',
    storageBucket: 'voxbridge-cf7be.firebasestorage.app',
    measurementId: 'G-JLJPZPGTXP',
  );
}
